name: Daily Penguin Prediction

on:
  schedule:
    - cron: '30 7 * * *'   # every day at 7:30 
  workflow_dispatch:       # allow manual runs

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependiences
        run: |
          pip install pandas scikit-learn joblib requests

      - name: Run prediction script
        run: python predict.py

      - name: Commit and push predictions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add prediction_output/prediction.html
          git commit -m " Daily prediction update"
          git push

